In [6]:
import pandas as pd

sales = pd.read_csv("../datasets/sales/DrugSalesData.csv")

inventory = pd.read_csv("../datasets/inventory/Inventory_Transactions.csv")

stock = pd.read_csv("../datasets/stock/synthetic_stock_data.csv")

medicine_price = pd.read_csv("../datasets/products/medicine_price_dataset.csv")

products = pd.read_csv("../datasets/products/pharma_products_dataset.csv")

ParserError: Error tokenizing data. C error: Expected 11 fields in line 9, saw 12

In [5]:
import os

print("Current Directory:")
print(os.getcwd())

print(os.listdir())

print("\nDatasets Folder Exists:")
print(os.path.exists("datasets"))

print("\nSales File Exists:")
print(os.path.exists("datasets/sales/DrugSalesData.csv"))

Current Directory:
c:\Users\hiii\OneDrive\Desktop\Smart-Pharmacy-Predictive-Analytics\notebooks
['01_dataset_profiling.ipynb']

Datasets Folder Exists:
False

Sales File Exists:
False

In [7]:
import os

print(os.getcwd())

c:\Users\hiii\OneDrive\Desktop\Smart-Pharmacy-Predictive-Analytics\notebooks

In [9]:
import os

print(os.listdir())

['01_dataset_profiling.ipynb']

In [10]:
import pandas as pd

sales = pd.read_csv("datasets/sales/DrugSalesData.csv")

sales.head()

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/sales/DrugSalesData.csv'

In [11]:
import os

print(
    os.path.exists("../datasets/sales/DrugSalesData.csv")
)

True

In [13]:
sales = pd.read_csv(
    "../datasets/sales/DrugSalesData.csv"
)

sales.head()

ParserError: Error tokenizing data. C error: Expected 11 fields in line 9, saw 12

In [ ]:
sales = pd.read_csv("../datasets/sales/DrugSalesData.csv")

ParserError: Error tokenizing data. C error: Expected 11 fields in line 9, saw 12

In [15]:
sales.head()

NameError: name 'sales' is not defined

In [ ]:
sales = pd.read_csv("../datasets/sales/DrugSalesData.csv")

print(sales.shape)
print(sales.columns.tolist())

ParserError: Error tokenizing data. C error: Expected 11 fields in line 9, saw 12

In [17]:
with open("../datasets/sales/DrugSalesData.csv", "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i < 15:
            print(f"Line {i+1}: {line}")

Line 1: ﻿Patient name;Company Name;DoctorNameSurname;Protocol;Drug Name;Medicine;Drug Dosage Expiry Date;Medicine;Medicine;Pickup Time;IlacReceteTutari;DrugSerNo;ReceteBrutTotal;Pharmacy;ERecete;EReceteNo;The patient's debt;PatientTour;Hkp;ReceteIlacFarki;Field of Medicine;ReceteDrug DomainName;Recipe;ReceteIndOnTop;Recetion;Public Discount;Salary;ReceteNetAmount;ReceteKP;RecipeDate;Reporting;NobetciMi;Season;ID;Drug Group;Receipt Date

Line 2: 662;39;812;13656;PURlNOL EFERVESAN 7O G GRANUL;1;11.05.2018 00:00;7,48;0;07.05.2018 08:51;176,47;;185,67;5,09;E;4927;29,64;WORKING;4,11;14,53;Itself;12894;;290,75;0;105,08;8;176,47;3;05.05.2018 00:00;1;0;İlkbahar;1;PURlNOL;07.05.2018

Line 3: 662;39;812;13656;COLNAR 1O MG 28 FlLM KAPLl TABLET;4;27.08.2018 00:00;39,23;5,68;07.05.2018 08:51;0;;185,67;5,09;E;4927;29,64;WORKING;4,11;14,53;Itself;12894;;290,75;0;105,08;8;176,47;3;05.05.2018 00:00;1;0;İlkbahar;2;COLNAR;07.05.2018

Line 4: 662;39;812;13656;CORASPlN 1OO MG 3O TABLET;3;19.08.2018 00:00;3,16;0;07.05.2018 08:51;0;;185,67;5,09;E;4927;29,64;WORKING;4,11;14,53;Itself;12894;;290,75;0;105,08;8;176,47;3;05.05.2018 00:00;1;0;İlkbahar;3;CORASPlN;07.05.2018

Line 5: 662;39;812;13656;DlAMlCRON MR 3O MG 6O TABLET;3;13.08.2018 00:00;13,68;7,53;07.05.2018 08:51;0;;185,67;5,09;E;4927;29,64;WORKING;4,11;14,53;Itself;12894;;290,75;0;105,08;8;176,47;3;05.05.2018 00:00;1;0;İlkbahar;4;DlAMlCRON;07.05.2018

Line 6: 662;39;812;13656;GLlFOR 85O MG 1OO FlLM TABLET;2;15.08.2018 00:00;19,36;1,32;07.05.2018 08:51;0;;185,67;5,09;E;4927;29,64;WORKING;4,11;14,53;Itself;12894;;290,75;0;105,08;8;176,47;3;05.05.2018 00:00;1;0;İlkbahar;5;GLlFOR;07.05.2018

Line 7: 662;39;812;13656;ClPRO 5OO MG 14 FlLM TABLET;1;14.05.2018 00:00;13,68;0;07.05.2018 08:51;0;;185,67;5,09;E;4927;29,64;WORKING;4,11;14,53;Itself;12894;;290,75;0;105,08;8;176,47;3;05.05.2018 00:00;1;0;İlkbahar;6;ClPRO;07.05.2018

Line 8: 662;39;812;13656;NORVASC 5 MG 9O TABLET;1;19.08.2018 00:00;23,43;0;07.05.2018 08:51;0;;185,67;5,09;E;4927;29,64;WORKING;4,11;14,53;Itself;12894;;290,75;0;105,08;8;176,47;3;05.05.2018 00:00;1;0;İlkbahar;7;NORVASC;07.05.2018

Line 9: 8050;16;402;2233;PANTO 4O MG 28 ENTERlK KAPLl TABLET;4;27.08.2018 00:00;24,62;12,2;07.05.2018 08:55;123,24;;132,48;3,56;E;7227;17,48;RETIRED;5,68;17,48;Relative;17386;;253,08;0;120,6;0;123,24;0;05.05.2018 00:00;1;0;İlkbahar;8;PANTO;07.05.2018

Line 10: 8050;16;402;2233;CRESTOR 1O MG 28 FlLM TABLET;4;29.08.2018 00:00;38,65;5,28;07.05.2018 08:55;0;;132,48;3,56;E;7227;17,48;RETIRED;5,68;17,48;Relative;17386;;253,08;0;120,6;0;123,24;0;05.05.2018 00:00;1;0;İlkbahar;9;CRESTOR;07.05.2018

Line 11: 9601;75;292;64675;NERUDA 3OO MG 5O FlLM TABLET;4;15.08.2018 00:00;24,45;1,32;07.05.2018 09:20;67,16;;69,04;1,88;E;10608;1,32;RETIRED;0;1,32;Relative;51665;;97,8;0;28,76;0;67,16;0;07.05.2018 00:00;0;0;İlkbahar;10;NERUDA;07.05.2018

Line 12: 2730;24;1250;13469;TANFLEX %O15  3O ML ORAL SPREY;1;01.01.1900 00:00;13,68;0;07.05.2018 09:27;76,81;;98,47;2,46;;9426;48,6;WORKING;19,2;29,4;;8;BOYS;98,47;0;0;0;76,81;0;07.05.2018 00:00;1;0;İlkbahar;11;TANFLEX;07.05.2018

Line 13: 2730;24;1250;13469;MlNOSET 5OO MG 2O TABLET;1;01.01.1900 00:00;2,89;0;07.05.2018 09:27;0;;98,47;2,46;;9426;48,6;WORKING;19,2;29,4;;8;BOYS;98,47;0;0;0;76,81;0;07.05.2018 00:00;1;0;İlkbahar;12;MlNOSET;07.05.2018

Line 14: 2730;24;1250;13469;UNACEFlN lM 1 G 1 FLAKON;6;01.01.1900 00:00;13,65;29,396952;07.05.2018 09:27;0;;98,47;2,46;;9426;48,6;WORKING;19,2;29,4;;8;BOYS;98,47;0;0;0;76,81;0;07.05.2018 00:00;1;0;İlkbahar;13;UNACEFlN;07.05.2018

Line 15: 4287;58;1101;55303;FUNlT 1OO MG 3O KAPSUL;1;14.05.2018 00:00;56,09;0;07.05.2018 10:53;35,35;;40,39;1,11;E;5402;0;RETIRED;3,93;0;Itself;55158;;56,09;0;15,7;0;35,35;0;07.05.2018 00:00;0;0;İlkbahar;14;FUNlT;07.05.2018

In [18]:
sales = pd.read_csv(
    "../datasets/sales/DrugSalesData.csv",
    on_bad_lines="skip"
)

print(sales.shape)
sales.head()

(57867, 1)

                                                                                                                                                                                                                                                        Patient name;Company Name;DoctorNameSurname;Protocol;Drug Name;Medicine;Drug Dosage Expiry Date;Medicine;Medicine;Pickup Time;IlacReceteTutari;DrugSerNo;ReceteBrutTotal;Pharmacy;ERecete;EReceteNo;The patient's debt;PatientTour;Hkp;ReceteIlacFarki;Field of Medicine;ReceteDrug DomainName;Recipe;ReceteIndOnTop;Recetion;Public Discount;Salary;ReceteNetAmount;ReceteKP;RecipeDate;Reporting;NobetciMi;Season;ID;Drug Group;Receipt Date
662;39;812;13656;PURlNOL EFERVESAN 7O G GRANUL;... 48;0;07.05.2018 08:51;176    47;;185                    67;5         09;E;4927;29 64;WORKING;4 11;14                53;Itself;12894;;290 75;0;105 08;8;176                                            47;3;05.05.2018 00:00;1;0;İlkbahar;1;PURlNOL;0...
662;39;812;13656;COLNAR 1O MG 28 FlLM KAPLl TAB... 23;5                         68;07.05.2018 08:51;0;;185 67;5         09;E;4927;29 64;WORKING;4 11;14                53;Itself;12894;;290 75;0;105 08;8;176                                            47;3;05.05.2018 00:00;1;0;İlkbahar;2;COLNAR;07...
662;39;812;13656;CORASPlN 1OO MG 3O TABLET;3;19... 16;0;07.05.2018 08:51;0;;185 67;5                       09;E;4927;29 64;WORKING;4 11;14        53;Itself;12894;;290 75;0;105             08;8;176 47;3;05.05.2018 00:00;1;0;İlkbahar;3;CORASPlN;0...                                                NaN
662;39;812;13656;DlAMlCRON MR 3O MG 6O TABLET;3... 68;7                         53;07.05.2018 08:51;0;;185 67;5         09;E;4927;29 64;WORKING;4 11;14                53;Itself;12894;;290 75;0;105 08;8;176                                            47;3;05.05.2018 00:00;1;0;İlkbahar;4;DlAMlCRON...
662;39;812;13656;GLlFOR 85O MG 1OO FlLM TABLET;... 36;1                         32;07.05.2018 08:51;0;;185 67;5         09;E;4927;29 64;WORKING;4 11;14                53;Itself;12894;;290 75;0;105 08;8;176                                            47;3;05.05.2018 00:00;1;0;İlkbahar;5;GLlFOR;07...

In [19]:
sales = pd.read_csv(
    "../datasets/sales/DrugSalesData.csv",
    delimiter=";"
)

C:\Users\hiii\AppData\Local\Temp\ipykernel_9204\866793637.py:1: DtypeWarning: Columns (11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  sales = pd.read_csv(

In [20]:
with open("../datasets/sales/DrugSalesData.csv", "r", encoding="utf-8") as f:
    print(f.readline())

Patient name;Company Name;DoctorNameSurname;Protocol;Drug Name;Medicine;Drug Dosage Expiry Date;Medicine;Medicine;Pickup Time;IlacReceteTutari;DrugSerNo;ReceteBrutTotal;Pharmacy;ERecete;EReceteNo;The patient's debt;PatientTour;Hkp;ReceteIlacFarki;Field of Medicine;ReceteDrug DomainName;Recipe;ReceteIndOnTop;Recetion;Public Discount;Salary;ReceteNetAmount;ReceteKP;RecipeDate;Reporting;NobetciMi;Season;ID;Drug Group;Receipt Date

In [21]:
print("Shape:", sales.shape)

print("\nColumns:")
print(sales.columns.tolist())

Shape: (64709, 36)

Columns:
['Patient name', 'Company Name', 'DoctorNameSurname', 'Protocol', 'Drug Name', 'Medicine', 'Drug Dosage Expiry Date', 'Medicine.1', 'Medicine.2', 'Pickup Time', 'IlacReceteTutari', 'DrugSerNo', 'ReceteBrutTotal', 'Pharmacy', 'ERecete', 'EReceteNo', "The patient's debt", 'PatientTour', 'Hkp', 'ReceteIlacFarki', 'Field of Medicine', 'ReceteDrug DomainName', 'Recipe', 'ReceteIndOnTop', 'Recetion', 'Public Discount', 'Salary', 'ReceteNetAmount', 'ReceteKP', 'RecipeDate', 'Reporting', 'NobetciMi', 'Season', 'ID', 'Drug Group', 'Receipt Date']

In [22]:
sales.head()

,Patient name,Company Name,DoctorNameSurname,Protocol,Drug Name,Medicine,Drug Dosage Expiry Date,Medicine.1,Medicine.2,Pickup Time,...,Salary,ReceteNetAmount,ReceteKP,RecipeDate,Reporting,NobetciMi,Season,ID,Drug Group,Receipt Date
0,662,39,812,13656,PURlNOL EFERVESAN 7O G GRANUL,1,11.05.2018 00:00,"7,48",0,07.05.2018 08:51,...,8,"176,47",3,05.05.2018 00:00,1,0,İlkbahar,1,PURlNOL,07.05.2018
1,662,39,812,13656,COLNAR 1O MG 28 FlLM KAPLl TABLET,4,27.08.2018 00:00,"39,23","5,68",07.05.2018 08:51,...,8,"176,47",3,05.05.2018 00:00,1,0,İlkbahar,2,COLNAR,07.05.2018
2,662,39,812,13656,CORASPlN 1OO MG 3O TABLET,3,19.08.2018 00:00,"3,16",0,07.05.2018 08:51,...,8,"176,47",3,05.05.2018 00:00,1,0,İlkbahar,3,CORASPlN,07.05.2018
3,662,39,812,13656,DlAMlCRON MR 3O MG 6O TABLET,3,13.08.2018 00:00,"13,68","7,53",07.05.2018 08:51,...,8,"176,47",3,05.05.2018 00:00,1,0,İlkbahar,4,DlAMlCRON,07.05.2018
4,662,39,812,13656,GLlFOR 85O MG 1OO FlLM TABLET,2,15.08.2018 00:00,"19,36","1,32",07.05.2018 08:51,...,8,"176,47",3,05.05.2018 00:00,1,0,İlkbahar,5,GLlFOR,07.05.2018